"use client";

import { Citation } from "./CitationList";

/**
 * PrintableResult — clean print/PDF rendering of a query result.
 *
 * Hidden on screen (`print-only`), revealed only when printing. Unlike the
 * interactive tabbed panel, this shows ALL three registers plus citations in one
 * linear document, with a provenance footer.
 */
interface PrintableResultProps {
  query: string;
  plainEnglish: string;
  legalLanguage: string;
  citations: Citation[];
  createdAt?: string;
}

function fmt(date?: string): string | null {
  if (!date) return null;
  const d = new Date(date.length <= 10 ? date + "T00:00:00" : date);
  if (isNaN(d.getTime())) return null;
  return d.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

export default function PrintableResult({
  query,
  plainEnglish,
  legalLanguage,
  citations,
  createdAt,
}: PrintableResultProps) {
  return (
    <div className="print-only printable-doc">
      <h1>Federal Regulation Query</h1>
      <p className="pd-question"><strong>Question:</strong> {query}</p>

      <h2>Plain-English Explanation</h2>
      <p className="pd-body">{plainEnglish}</p>

      <h2>Legal / Regulatory Language</h2>
      <p className="pd-body">{legalLanguage}</p>

      <h2>CFR Citations</h2>
      <ol className="pd-citations">
        {citations.map((c, i) => (
          <li key={i}>
            <strong>{c.cfr_reference}</strong>
            {c.section_heading ? ` — ${c.section_heading}` : ""}
            {c.agency ? ` (${c.agency})` : ""}
            {fmt(c.effective_date) ? ` · current as of ${fmt(c.effective_date)}` : ""}
          </li>
        ))}
      </ol>

      <footer className="pd-footer">
        Generated by Federal Regulation Query (regs.bradhinkel.com) from the U.S.
        eCFR{fmt(createdAt) ? ` · retrieved ${fmt(createdAt)}` : ""}. Verify against
        the official eCFR at ecfr.gov before relying on this text.
      </footer>
    </div>
  );
}
